# Generated by Django 4.1.1 on 2022-09-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0004_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('yes', 'yes'), ('no', 'no')]),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
