# Generated by Django 4.1.1 on 2022-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(verbose_name='Order_date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'zatwierdzony'), (2, 'niezatwierdzony')], null=True),
        ),
    ]
