# Generated by Django 4.1.1 on 2022-09-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0007_alter_order_deadline_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(blank=True, to='Cakes.websiteuser'),
        ),
    ]
