# Generated by Django 4.1.1 on 2022-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0008_remove_order_user_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='website_users',
        ),
    ]
