# Generated by Django 4.1.1 on 2022-09-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0009_rename_user_order_website_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='website_users',
        ),
        migrations.AddField(
            model_name='order',
            name='website_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cakes.websiteuser'),
        ),
    ]
