# Generated by Django 4.1.1 on 2022-09-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'W trakcie przetwarzania'), (2, 'Zamówienie zatwierdzone! Skontaktujemy się z tobą w ciągu dwóch dni!'), (3, 'Niestety nie jesteśmy w stanie zrealizować twojego zamówienia,     o więcej informacji zgłoś się do naszej obsługi klienta.')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cakes.product'),
        ),
    ]
