# Generated by Django 4.1.1 on 2022-09-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0013_remove_ingredients_product_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cakes.ingredients'),
        ),
    ]
