# Generated by Django 4.1.1 on 2022-09-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cakes.product', verbose_name='produkt'),
        ),
    ]
