# Generated by Django 4.0.2 on 2022-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0018_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ManyToManyField(to='Cakes.Product'),
        ),
    ]
