# Generated by Django 4.0.2 on 2022-09-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0019_remove_ingredients_product_ingredients_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='Ingredient_list',
            field=models.ManyToManyField(to='Cakes.Ingredients'),
        ),
    ]
