# Generated by Django 4.0.2 on 2022-09-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0020_remove_ingredients_product_product_ingredient_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredient_list',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cakes.product'),
        ),
    ]
