# Generated by Django 4.0.2 on 2022-09-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0021_remove_product_ingredient_list_ingredients_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='product',
        ),
    ]
