# Generated by Django 4.0.2 on 2022-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0022_remove_ingredients_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients_list',
            field=models.ManyToManyField(blank=True, to='Cakes.Ingredients'),
        ),
    ]
